'use client';

import React, { useState, useEffect, useRef } from 'react';
import { Search, X } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';

import { useRouter } from 'next/navigation';

// Basic structured index of our documentation content
const searchIndex = [
  { id: 'introduction', url: '/docs#what-is-novaire', title: 'What is Novaire?', type: 'heading', content: 'Novaire is a decentralized finance protocol built on the Stellar network using Soroban smart contracts. It enables the strict separation of yield-bearing assets into their principal and future yield components.' },
  { id: 'why-novaire', url: '/docs#why-novaire', title: 'Why Novaire?', type: 'heading', content: 'Yield in decentralized finance is inherently volatile and fragmented. Institutional and retail investors face significant risks when deploying capital into variable-rate money markets.' },
  { id: 'how-it-works', url: '/docs#how-it-works', title: 'How it Works', type: 'heading', content: 'The protocol operates via a system of interacting smart contracts that manage the asset lifecycle from deposit to maturity.' },
  { id: 'core-concepts', url: '/docs#core-concepts', title: 'Core Concepts', type: 'heading', content: 'Standardized Yield (SY), Vaults, Principal Tokens (PT), Yield Tokens (YT), Tokenizer, Marketplace, Intent Engine' },
  { id: 'standardized-yield', url: '/docs#standardized-yield', title: 'Standardized Yield (SY)', type: 'heading', content: 'SY is a standardized token wrapper that homogenizes disparate yield-bearing assets into a common accounting interface.' },
  { id: 'vaults', url: '/docs#vaults', title: 'Vaults', type: 'heading', content: 'The central treasury that secures underlying assets (like XLM or USDC) and issues SY shares to depositors.' },
  { id: 'principal-tokens', url: '/docs#principal-tokens', title: 'Principal Tokens (PT)', type: 'heading', content: 'A claim on the base principal of an asset, redeemable 1:1 at a specific future maturity date.' },
  { id: 'yield-tokens', url: '/docs#yield-tokens', title: 'Yield Tokens (YT)', type: 'heading', content: 'A claim on all variable yield generated by the underlying principal until the maturity date.' },
  { id: 'tokenizer', url: '/docs#tokenizer', title: 'Tokenizer', type: 'heading', content: 'The core yield-stripping engine that issues PT and YT.' },
  { id: 'marketplace', url: '/docs#marketplace', title: 'Marketplace', type: 'heading', content: 'A custom Yield-Space Automated Market Maker (AMM) enabling the trading of PT and YT against the underlying asset.' },
  { id: 'intent-engine', url: '/docs#intent-engine', title: 'Intent Engine', type: 'heading', content: 'An abstract transaction router that executes multi-step retail strategies in a single transaction.' },
  { id: 'investment-strategies', url: '/docs/trading-yield#investment-strategies', title: 'Investment Strategies', type: 'heading', content: 'Keep All Yield, Fixed Yield, Custom Split.' },
  { id: 'protocol-architecture', url: '/docs/developers#protocol-architecture', title: 'Protocol Architecture', type: 'heading', content: 'Novaire separates its logic into highly specialized Soroban smart contracts to maintain strict security boundaries.' },
  { id: 'yield-lifecycle', url: '/docs/trading-yield#yield-lifecycle', title: 'Yield Lifecycle', type: 'heading', content: 'The Tokenizer mints PT and YT against deposited SY shares. As yield accrues natively to the SY shares in the Vault, the exchange rate climbs.' },
  { id: 'market-mechanics', url: '/docs/trading-yield#market-mechanics', title: 'Market Mechanics', type: 'heading', content: 'Because PT is a zero-coupon bond, it must mathematically converge to 1.0 (relative to the underlying asset) as the maturity date approaches.' },
  { id: 'marketplace-deep-dive', url: '/docs/trading-yield#marketplace-deep-dive', title: 'Marketplace Deep Dive', type: 'heading', content: 'Market Driven Pricing, TWAP (Time-Weighted Average Price).' },
  { id: 'portfolio-analytics', url: '/docs/trading-yield#portfolio-analytics', title: 'Portfolio & Analytics', type: 'heading', content: 'Portfolio Value, Claimable Yield.' },
  { id: 'automation-features', url: '/docs/trading-yield#automation-features', title: 'Automation Features', type: 'heading', content: 'Auto Rollovers. Unlike perpetual markets, Novaire operates in distinct epochs with fixed maturity dates.' },
  { id: 'developers', url: '/docs/developers#developers', title: 'Developers', type: 'heading', content: 'Smart Contracts API, Integration Guide.' },
  { id: 'faq', url: '/docs/developers#faq', title: 'FAQ', type: 'heading', content: 'Are my funds locked until maturity? What happens if I don\'t redeem at maturity? Is Novaire audited?' }
];

export function DocsSearch() {
  const router = useRouter();
  const [isOpen, setIsOpen] = useState(false);
  const [query, setQuery] = useState('');
  const [selectedIndex, setSelectedIndex] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);

  // Keyboard shortcut to open search
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === '/' && !isOpen) {
        e.preventDefault();
        setIsOpen(true);
      }
      if (e.key === 'Escape' && isOpen) {
        setIsOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen]);

  useEffect(() => {
    if (isOpen) {
      setTimeout(() => inputRef.current?.focus(), 100);
      document.body.style.overflow = 'hidden';
    } else {
      setQuery('');
      document.body.style.overflow = 'unset';
    }
    return () => {
      document.body.style.overflow = 'unset';
    };
  }, [isOpen]);

  const results = query
    ? searchIndex.filter(
        (item) =>
          item.title.toLowerCase().includes(query.toLowerCase()) ||
          item.content.toLowerCase().includes(query.toLowerCase())
      )
    : [];

  useEffect(() => {
    setSelectedIndex(0);
  }, [query]);

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'ArrowDown') {
      e.preventDefault();
      setSelectedIndex((prev) => (prev < results.length - 1 ? prev + 1 : prev));
    } else if (e.key === 'ArrowUp') {
      e.preventDefault();
      setSelectedIndex((prev) => (prev > 0 ? prev - 1 : prev));
    } else if (e.key === 'Enter' && results.length > 0) {
      e.preventDefault();
      handleSelect(results[selectedIndex].url);
    }
  };

  const handleSelect = (url: string) => {
    setIsOpen(false);
    setTimeout(() => {
      router.push(url);
    }, 50);
  };

  const highlightMatch = (text: string, term: string) => {
    if (!term) return text;
    const parts = text.split(new RegExp(`(${term})`, 'gi'));
    return (
      <>
        {parts.map((part, i) =>
          part.toLowerCase() === term.toLowerCase() ? (
            <span key={i} className="text-[#3ECF8E] font-medium bg-[#3ECF8E]/10 rounded px-0.5">
              {part}
            </span>
          ) : (
            <span key={i}>{part}</span>
          )
        )}
      </>
    );
  };

  return (
    <>
      <div 
        className="relative w-full cursor-text group" 
        onClick={() => setIsOpen(true)}
      >
        <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
          <Search className="h-5 w-5 text-gray-400 group-hover:text-[#3ECF8E] transition-colors" aria-hidden="true" />
        </div>
        <div className="block w-full rounded-full border border-white/5 bg-white/5 py-2 pl-10 pr-3 text-sm text-gray-400 group-hover:bg-white/10 group-hover:border-white/10 transition-colors">
          Search documentation...
          <span className="absolute right-3 top-2 text-xs text-gray-500 border border-gray-700 rounded px-1.5 py-0.5 hidden sm:inline-block">/</span>
        </div>
      </div>

      <AnimatePresence>
        {isOpen && (
          <>
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-[100] bg-black/80 backdrop-blur-sm"
              onClick={() => setIsOpen(false)}
            />
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: -20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: -20 }}
              className="fixed inset-x-4 top-20 z-[101] mx-auto max-w-2xl rounded-2xl bg-gray-900 border border-white/10 shadow-2xl overflow-hidden"
            >
              <div className="flex items-center border-b border-white/10 px-4 py-4">
                <Search className="h-5 w-5 text-gray-400" />
                <input
                  ref={inputRef}
                  type="text"
                  className="w-full bg-transparent border-0 focus:ring-0 text-white placeholder-gray-500 px-4 outline-none"
                  placeholder="Search documentation..."
                  value={query}
                  onChange={(e) => setQuery(e.target.value)}
                  onKeyDown={handleKeyDown}
                />
                <button 
                  onClick={() => setIsOpen(false)}
                  className="text-gray-400 hover:text-white p-1 rounded-md hover:bg-white/10 transition-colors"
                >
                  <X className="h-5 w-5" />
                </button>
              </div>

              {query && (
                <div className="max-h-[60vh] overflow-y-auto p-2">
                  {results.length > 0 ? (
                    <ul className="space-y-1">
                      {results.map((result, idx) => (
                        <li key={result.id}>
                          <button
                            className={`w-full text-left px-4 py-3 rounded-lg transition-colors flex flex-col gap-1 ${
                              idx === selectedIndex ? 'bg-[#3ECF8E]/10' : 'hover:bg-white/5'
                            }`}
                            onClick={() => handleSelect(result.id)}
                            onMouseEnter={() => setSelectedIndex(idx)}
                          >
                            <span className={`font-medium ${idx === selectedIndex ? 'text-[#3ECF8E]' : 'text-white'}`}>
                              {highlightMatch(result.title, query)}
                            </span>
                            <span className="text-sm text-gray-400 line-clamp-2">
                              {highlightMatch(result.content, query)}
                            </span>
                          </button>
                        </li>
                      ))}
                    </ul>
                  ) : (
                    <div className="px-4 py-12 text-center text-gray-400">
                      No results found for &quot;{query}&quot;
                    </div>
                  )}
                </div>
              )}
              
              <div className="border-t border-white/10 px-4 py-3 bg-black/50 text-xs text-gray-500 flex items-center justify-end gap-4 hidden sm:flex">
                <span className="flex items-center gap-1">
                  <kbd className="border border-gray-700 rounded px-1">↓</kbd>
                  <kbd className="border border-gray-700 rounded px-1">↑</kbd> to navigate
                </span>
                <span className="flex items-center gap-1">
                  <kbd className="border border-gray-700 rounded px-1">Enter</kbd> to select
                </span>
                <span className="flex items-center gap-1">
                  <kbd className="border border-gray-700 rounded px-1">Esc</kbd> to close
                </span>
              </div>
            </motion.div>
          </>
        )}
      </AnimatePresence>
    </>
  );
}
